name: Verify publish rights
on:
  pull_request:
    paths:
      - .github/workflows/verify-publish-rights.yaml

jobs:
  verify:
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 20.x
      - run: npm install -g @vscode/vsce
      - uses: azure/login@7ddb5af1ef8758cf1353cf3b42f940aee27ba21c # v3.0.2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
      - env:
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: vsce verify-pat MetalBear --azure-credential
